// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by pipeline:
//     go
// Using jennies:
//     GoTypesJenny
//     ComposableLatestMajorsOrXJenny
//
// Run 'go generate ./' from repository root to regenerate.

package candlestickpanelcfg

// PanelFieldConfig defines model for PanelFieldConfig.
type PanelFieldConfig = map[string]interface{}

// PanelOptions defines model for PanelOptions.
type PanelOptions = map[string]interface{}
