// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by pipeline:
//     go
// Using jennies:
//     GoTypesJenny
//     ComposableLatestMajorsOrXJenny
//
// Run 'go generate ./' from repository root to regenerate.

package logspanelcfg

// Defines values for LogsDedupStrategy.
const (
	LogsDedupStrategyExact     LogsDedupStrategy = "exact"
	LogsDedupStrategyNone      LogsDedupStrategy = "none"
	LogsDedupStrategyNumbers   LogsDedupStrategy = "numbers"
	LogsDedupStrategySignature LogsDedupStrategy = "signature"
)

// Defines values for LogsSortOrder.
const (
	LogsSortOrderAscending  LogsSortOrder = "Ascending"
	LogsSortOrderDescending LogsSortOrder = "Descending"
)

// LogsDedupStrategy defines model for LogsDedupStrategy.
type LogsDedupStrategy string

// LogsSortOrder defines model for LogsSortOrder.
type LogsSortOrder string

// PanelOptions defines model for PanelOptions.
type PanelOptions struct {
	DedupStrategy      LogsDedupStrategy `json:"dedupStrategy"`
	EnableLogDetails   bool              `json:"enableLogDetails"`
	PrettifyLogMessage bool              `json:"prettifyLogMessage"`
	ShowCommonLabels   bool              `json:"showCommonLabels"`
	ShowLabels         bool              `json:"showLabels"`
	ShowTime           bool              `json:"showTime"`
	SortOrder          LogsSortOrder     `json:"sortOrder"`
	WrapLogMessage     bool              `json:"wrapLogMessage"`
}
