// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by pipeline:
//     go
// Using jennies:
//     TypedSchemaJenny
//     LatestMajorsOrXJenny
//
// Run 'go generate ./' from repository root to regenerate.

package preferences

import (
	"fmt"
	"sync"

	"github.com/grafana/grafana/pkg/registry/corekind"
	"github.com/grafana/thema"
)

// KindVersion is the syntactic version of the canonical schema from which this
// package's '[Preferences] type was generated.
//
// This value will always be the same as calling Schema().Version().
var KindVersion thema.SyntacticVersion = [2]uint{0, 0}

var schemaOnce sync.Once
var tschema thema.TypedSchema[*Preferences]

// Schema returns the [thema.TypedSchema] representing the schema from which
// the [Preferences] type and its referenced subtypes (if any) were generated.
func Schema() thema.TypedSchema[*Preferences] {
	reg := corekind.NewBase(nil)
	sch := thema.SchemaP(reg.Preferences().Lineage(), thema.SV(0, 0))
	schemaOnce.Do(func() {
		var err error
		tschema, err = thema.BindType[*Preferences](sch, new(Preferences))
		if err != nil {
			panic(fmt.Sprintf("preferences@0.0 is not assignable to *preferences: %s", err))
		}
	})
	return tschema
}

// NewWithDefaults returns a new [Preferences] that has been initialized with
// schema-specified default values.
func NewWithDefaults() *Preferences {
	return Schema().NewT()
}
