// This file is autogenerated. DO NOT EDIT.
//
// Run "go generate ./..." from the grok repository root to regenerate.

package goschemadashboard

import (
	"github.com/grafana/thema"
)

// Version indicates the syntactic version of the schema from which the Go
// code in this package was generated.
func Version() thema.SyntacticVersion {
	return thema.SV(0, 0)
}
