// This file is autogenerated. DO NOT EDIT.
//
// Run "go generate ./..." from the grok repository root to regenerate.

package goschemadashboard

import (
	"github.com/grafana/grafana/pkg/framework/coremodel/registry"
	"github.com/grafana/thema"
)

// Version is the syntactic version of the schema from which the Go
// code in this package was generated.
//
// This value will always be the same as calling Schema().Version().
var Version thema.SyntacticVersion = [2]uint{0, 0}

// Schema returns the schema from which the Go code in this package was generated.
//
// This uses the central thema.Library and cue.Context provided in github.com/grafana/grafana/pkg/cuectx.
// If you must provide your own, call github.com/grafana/grafana/pkg/coremodel/dashboard.Lineage() directly.
func Schema() thema.Schema {
	reg := registry.NewBase()
	return thema.SchemaP(reg.Dashboard().Lineage(), thema.SV(0, 0))
}
