// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by pipeline:
//     terraform
// Using jennies:
//     TerraformDataSourceJenny
//     LatestJenny
//
// Run 'go generate ./' from repository root to regenerate.

package datasources

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/grafana/terraform-provider-grafana-framework/internal/common"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ datasource.DataSource              = &teamDataSource{}
	_ datasource.DataSourceWithConfigure = &teamDataSource{}
)

func NewteamDataSource() datasource.DataSource {
	return &teamDataSource{}
}

// teamDataSource defines the data source implementation.
type teamDataSource struct {
	client *common.Client
}

// teamDataSourceModel describes the data source data model.
type teamDataSourceModel struct {
	OrgId         types.Int64  `tfsdk:"orgId", json:"orgId"`
	Name          types.String `tfsdk:"name", json:"name"`
	Email         types.String `tfsdk:"email", json:"email"`
	AvatarUrl     types.String `tfsdk:"avatarUrl", json:"avatarUrl"`
	MemberCount   types.Int64  `tfsdk:"memberCount", json:"memberCount"`
	Permission    types.Int64  `tfsdk:"permission", json:"permission"`
	AccessControl types.Object `tfsdk:"accessControl", json:"accessControl"`
	Created       types.Int64  `tfsdk:"created", json:"created"`
	Updated       types.Int64  `tfsdk:"updated", json:"updated"`
	ToJSON        types.String `tfsdk:"to_json"`
}

func (d *teamDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_team"
}

func (d *teamDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		// This description is used by the documentation generator and the language server.
		MarkdownDescription: "TODO description",

		Attributes: map[string]schema.Attribute{
			"orgId": schema.Int64Attribute{
				MarkdownDescription: `OrgId is the ID of an organisation the team belongs to.`,
				Computed:            false,
				Optional:            false,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: `Name of the team.`,
				Computed:            false,
				Optional:            false,
			},
			"email": schema.StringAttribute{
				MarkdownDescription: `Email of the team.`,
				Computed:            false,
				Optional:            true,
			},
			"avatarUrl": schema.StringAttribute{
				MarkdownDescription: `AvatarUrl is the team's avatar URL.`,
				Computed:            false,
				Optional:            true,
			},
			"memberCount": schema.Int64Attribute{
				MarkdownDescription: `MemberCount is the number of the team members.`,
				Computed:            false,
				Optional:            false,
			},
			"permission": schema.Int64Attribute{
				MarkdownDescription: `TODO - it seems it's a team_member.permission, unlikely it should belong to the team kind`,
				Computed:            false,
				Optional:            false,
			},
			"accessControl": schema.ObjectAttribute{
				MarkdownDescription: `AccessControl metadata associated with a given resource.`,
				Computed:            false,
				Optional:            true,
			},
			"created": schema.Int64Attribute{
				MarkdownDescription: `Created indicates when the team was created.`,
				Computed:            false,
				Optional:            false,
			},
			"updated": schema.Int64Attribute{
				MarkdownDescription: `Updated indicates when the team was updated.`,
				Computed:            false,
				Optional:            false,
			},
			"to_json": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "This datasource rendered as JSON",
			},
		},
	}
}

func (d *teamDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*common.Client)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *common.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	d.client = client
}

func (d *teamDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data teamDataSourceModel

	// Read Terraform configuration data into the model
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	JSONConfig, err := json.Marshal(data)
	if err != nil {
		resp.Diagnostics.AddError("JSON marshalling error", err.Error())
		return
	}

	// Not sure about that
	data.ToJSON = types.StringValue(string(JSONConfig))

	// Write logs using the tflog package
	// Documentation: https://terraform.io/plugin/log
	tflog.Trace(ctx, "read a data source")

	// Save data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
