// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by pipeline:
//     go
// Using jennies:
//     GoTypesJenny
//     ComposableLatestMajorsOrXJenny
//
// Run 'go generate ./' from repository root to regenerate.

package xychartpanelcfg

// Defines values for AxisColorMode.
const (
	AxisColorModeSeries AxisColorMode = "series"

	AxisColorModeText AxisColorMode = "text"
)

// Defines values for AxisPlacement.
const (
	AxisPlacementAuto AxisPlacement = "auto"

	AxisPlacementBottom AxisPlacement = "bottom"

	AxisPlacementHidden AxisPlacement = "hidden"

	AxisPlacementLeft AxisPlacement = "left"

	AxisPlacementRight AxisPlacement = "right"

	AxisPlacementTop AxisPlacement = "top"
)

// Defines values for LegendDisplayMode.
const (
	LegendDisplayModeHidden LegendDisplayMode = "hidden"

	LegendDisplayModeList LegendDisplayMode = "list"

	LegendDisplayModeTable LegendDisplayMode = "table"
)

// Defines values for LegendPlacement.
const (
	LegendPlacementBottom LegendPlacement = "bottom"

	LegendPlacementRight LegendPlacement = "right"
)

// Defines values for LineStyleFill.
const (
	LineStyleFillDash LineStyleFill = "dash"

	LineStyleFillDot LineStyleFill = "dot"

	LineStyleFillSolid LineStyleFill = "solid"

	LineStyleFillSquare LineStyleFill = "square"
)

// Defines values for ScaleDistribution.
const (
	ScaleDistributionLinear ScaleDistribution = "linear"

	ScaleDistributionLog ScaleDistribution = "log"

	ScaleDistributionOrdinal ScaleDistribution = "ordinal"

	ScaleDistributionSymlog ScaleDistribution = "symlog"
)

// Defines values for ScatterShow.
const (
	ScatterShowLines ScatterShow = "lines"

	ScatterShowPoints ScatterShow = "points"

	ScatterShowPointsLines ScatterShow = "points+lines"
)

// Defines values for SeriesMapping.
const (
	SeriesMappingAuto SeriesMapping = "auto"

	SeriesMappingManual SeriesMapping = "manual"
)

// Defines values for SortOrder.
const (
	SortOrderAsc SortOrder = "asc"

	SortOrderDesc SortOrder = "desc"

	SortOrderNone SortOrder = "none"
)

// Defines values for TextDimensionMode.
const (
	TextDimensionModeField TextDimensionMode = "field"

	TextDimensionModeFixed TextDimensionMode = "fixed"

	TextDimensionModeTemplate TextDimensionMode = "template"
)

// Defines values for TooltipDisplayMode.
const (
	TooltipDisplayModeMulti TooltipDisplayMode = "multi"

	TooltipDisplayModeNone TooltipDisplayMode = "none"

	TooltipDisplayModeSingle TooltipDisplayMode = "single"
)

// Defines values for VisibilityMode.
const (
	VisibilityModeAlways VisibilityMode = "always"

	VisibilityModeAuto VisibilityMode = "auto"

	VisibilityModeNever VisibilityMode = "never"
)

// TODO docs
type AxisColorMode string

// TODO docs
type AxisConfig struct {
	AxisCenteredZero *bool `json:"axisCenteredZero,omitempty"`

	// TODO docs
	AxisColorMode *AxisColorMode `json:"axisColorMode,omitempty"`
	AxisGridShow  *bool          `json:"axisGridShow,omitempty"`
	AxisLabel     *string        `json:"axisLabel,omitempty"`

	// TODO docs
	AxisPlacement *AxisPlacement `json:"axisPlacement,omitempty"`
	AxisSoftMax   *float32       `json:"axisSoftMax,omitempty"`
	AxisSoftMin   *float32       `json:"axisSoftMin,omitempty"`
	AxisWidth     *float32       `json:"axisWidth,omitempty"`

	// TODO docs
	ScaleDistribution *ScaleDistributionConfig `json:"scaleDistribution,omitempty"`
}

// TODO docs
type AxisPlacement string

// BaseDimensionConfig defines model for BaseDimensionConfig.
type BaseDimensionConfig struct {
	Field *string     `json:"field,omitempty"`
	Fixed interface{} `json:"fixed"`
}

// ColorDimensionConfig defines model for ColorDimensionConfig.
type ColorDimensionConfig struct {
	// Embedded struct due to allOf(#/components/schemas/BaseDimensionConfig)
	BaseDimensionConfig `yaml:",inline"`
}

// TODO docs
type HideSeriesConfig struct {
	Legend  bool `json:"legend"`
	Tooltip bool `json:"tooltip"`
	Viz     bool `json:"viz"`
}

// TODO docs
type HideableFieldConfig struct {
	// TODO docs
	HideFrom *HideSeriesConfig `json:"hideFrom,omitempty"`
}

// TODO docs
// Note: "hidden" needs to remain as an option for plugins compatibility
type LegendDisplayMode string

// TODO docs
type LegendPlacement string

// TODO docs
type LineStyle struct {
	Dash *[]float32     `json:"dash,omitempty"`
	Fill *LineStyleFill `json:"fill,omitempty"`
}

// LineStyleFill defines model for LineStyle.Fill.
type LineStyleFill string

// TODO docs
type OptionsWithLegend struct {
	// TODO docs
	Legend VizLegendOptions `json:"legend"`
}

// TODO docs
type OptionsWithTooltip struct {
	// TODO docs
	Tooltip VizTooltipOptions `json:"tooltip"`
}

// PanelOptions defines model for PanelOptions.
type PanelOptions struct {
	// Embedded struct due to allOf(#/components/schemas/OptionsWithLegend)
	OptionsWithLegend `yaml:",inline"`
	// Embedded struct due to allOf(#/components/schemas/OptionsWithTooltip)
	OptionsWithTooltip `yaml:",inline"`
	// Embedded fields due to inline allOf schema
}

// ScaleDimensionConfig defines model for ScaleDimensionConfig.
type ScaleDimensionConfig struct {
	// Embedded struct due to allOf(#/components/schemas/BaseDimensionConfig)
	BaseDimensionConfig `yaml:",inline"`
	// Embedded fields due to inline allOf schema
}

// TODO docs
type ScaleDistribution string

// TODO docs
type ScaleDistributionConfig struct {
	LinearThreshold *float32 `json:"linearThreshold,omitempty"`
	Log             *float32 `json:"log,omitempty"`

	// TODO docs
	Type ScaleDistribution `json:"type"`
}

// ScatterFieldConfig defines model for ScatterFieldConfig.
type ScatterFieldConfig struct {
	// Embedded struct due to allOf(#/components/schemas/HideableFieldConfig)
	HideableFieldConfig `yaml:",inline"`
	// Embedded struct due to allOf(#/components/schemas/AxisConfig)
	AxisConfig `yaml:",inline"`
}

// ScatterSeriesConfig defines model for ScatterSeriesConfig.
type ScatterSeriesConfig struct {
	// Embedded struct due to allOf(#/components/schemas/ScatterFieldConfig)
	ScatterFieldConfig `yaml:",inline"`
}

// ScatterShow defines model for ScatterShow.
type ScatterShow string

// SeriesMapping defines model for SeriesMapping.
type SeriesMapping string

// TODO docs
type SortOrder string

// TextDimensionConfig defines model for TextDimensionConfig.
type TextDimensionConfig struct {
	// Embedded struct due to allOf(#/components/schemas/BaseDimensionConfig)
	BaseDimensionConfig `yaml:",inline"`
	// Embedded fields due to inline allOf schema
}

// TextDimensionMode defines model for TextDimensionMode.
type TextDimensionMode string

// TODO docs
type TooltipDisplayMode string

// TODO docs
type VisibilityMode string

// TODO docs
type VizLegendOptions struct {
	AsTable *bool    `json:"asTable,omitempty"`
	Calcs   []string `json:"calcs"`

	// TODO docs
	// Note: "hidden" needs to remain as an option for plugins compatibility
	DisplayMode LegendDisplayMode `json:"displayMode"`
	IsVisible   *bool             `json:"isVisible,omitempty"`

	// TODO docs
	Placement  LegendPlacement `json:"placement"`
	ShowLegend bool            `json:"showLegend"`
	SortBy     *string         `json:"sortBy,omitempty"`
	SortDesc   *bool           `json:"sortDesc,omitempty"`
	Width      *float32        `json:"width,omitempty"`
}

// TODO docs
type VizTooltipOptions struct {
	// TODO docs
	Mode TooltipDisplayMode `json:"mode"`

	// TODO docs
	Sort SortOrder `json:"sort"`
}

// XYDimensionConfig defines model for XYDimensionConfig.
type XYDimensionConfig struct {
	Exclude *[]string `json:"exclude,omitempty"`
	Frame   int       `json:"frame"`
	X       *string   `json:"x,omitempty"`
}
