// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by pipeline:
//     jsonnet
// Using jennies:
//     JsonnetImportsComposableJenny
//
// Run 'go generate ./' from repository root to regenerate.

[
  import "github.com/grafana/grok/jsonschema/kinds/core/dashboard/x/dashboard_types_gen.json",
  import "github.com/grafana/grok/jsonschema/kinds/core/librarypanel/x/librarypanel_types_gen.json",
  import "github.com/grafana/grok/jsonschema/kinds/composable/PhlareDataQuery/dataquery/x/PhlareDataQuery_types_gen.json",
  import "github.com/grafana/grok/jsonschema/kinds/composable/TempoDataQuery/dataquery/x/TempoDataQuery_types_gen.json",
  import "github.com/grafana/grok/jsonschema/kinds/composable/TestDataDataQuery/dataquery/x/TestDataDataQuery_types_gen.json",
  import "github.com/grafana/grok/jsonschema/kinds/composable/AnnotationsListPanelCfg/panelcfg/x/AnnotationsListPanelCfg_types_gen.json",
  import "github.com/grafana/grok/jsonschema/kinds/composable/BarChartPanelCfg/panelcfg/x/BarChartPanelCfg_types_gen.json",
  import "github.com/grafana/grok/jsonschema/kinds/composable/BarGaugePanelCfg/panelcfg/x/BarGaugePanelCfg_types_gen.json",
  import "github.com/grafana/grok/jsonschema/kinds/composable/DashboardListPanelCfg/panelcfg/x/DashboardListPanelCfg_types_gen.json",
  import "github.com/grafana/grok/jsonschema/kinds/composable/GaugePanelCfg/panelcfg/x/GaugePanelCfg_types_gen.json",
  import "github.com/grafana/grok/jsonschema/kinds/composable/HistogramPanelCfg/panelcfg/x/HistogramPanelCfg_types_gen.json",
  import "github.com/grafana/grok/jsonschema/kinds/composable/NewsPanelCfg/panelcfg/x/NewsPanelCfg_types_gen.json",
  import "github.com/grafana/grok/jsonschema/kinds/composable/NodeGraphPanelCfg/panelcfg/x/NodeGraphPanelCfg_types_gen.json",
  import "github.com/grafana/grok/jsonschema/kinds/composable/PieChartPanelCfg/panelcfg/x/PieChartPanelCfg_types_gen.json",
  import "github.com/grafana/grok/jsonschema/kinds/composable/StatPanelCfg/panelcfg/x/StatPanelCfg_types_gen.json",
  import "github.com/grafana/grok/jsonschema/kinds/composable/StateTimelinePanelCfg/panelcfg/x/StateTimelinePanelCfg_types_gen.json",
  import "github.com/grafana/grok/jsonschema/kinds/composable/StatusHistoryPanelCfg/panelcfg/x/StatusHistoryPanelCfg_types_gen.json",
  import "github.com/grafana/grok/jsonschema/kinds/composable/TextPanelCfg/panelcfg/x/TextPanelCfg_types_gen.json",
  import "github.com/grafana/grok/jsonschema/kinds/composable/XYChartPanelCfg/panelcfg/x/XYChartPanelCfg_types_gen.json",
]
