// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by pipeline:
//     jsonnet
// Using jennies:
//     JsonnetImportsCoreJenny
//
// Run 'go generate ./' from repository root to regenerate.

[
  import "./kinds/core/dashboard/x/dashboard_types_gen.json",
  import "./kinds/core/librarypanel/x/librarypanel_types_gen.json",
  import "./kinds/composable/phlare/dataquery/x/phlare_types_gen.json",
  import "./kinds/composable/tempo/dataquery/x/tempo_types_gen.json",
  import "./kinds/composable/testdata/dataquery/x/testdata_types_gen.json",
  import "./kinds/composable/annotationslist/panelcfg/x/annotationslist_types_gen.json",
  import "./kinds/composable/barchart/panelcfg/x/barchart_types_gen.json",
  import "./kinds/composable/bargauge/panelcfg/x/bargauge_types_gen.json",
  import "./kinds/composable/dashboardlist/panelcfg/x/dashboardlist_types_gen.json",
  import "./kinds/composable/gauge/panelcfg/x/gauge_types_gen.json",
  import "./kinds/composable/histogram/panelcfg/x/histogram_types_gen.json",
  import "./kinds/composable/news/panelcfg/x/news_types_gen.json",
  import "./kinds/composable/nodegraph/panelcfg/x/nodegraph_types_gen.json",
  import "./kinds/composable/piechart/panelcfg/x/piechart_types_gen.json",
  import "./kinds/composable/stat/panelcfg/x/stat_types_gen.json",
  import "./kinds/composable/statetimeline/panelcfg/x/statetimeline_types_gen.json",
  import "./kinds/composable/statushistory/panelcfg/x/statushistory_types_gen.json",
  import "./kinds/composable/text/panelcfg/x/text_types_gen.json",
  import "./kinds/composable/xychart/panelcfg/x/xychart_types_gen.json",
]
