// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by pipeline:
//     go
// Using jennies:
//     GoTypesJenny
//     ComposableLatestMajorsOrXJenny
//
// Run 'go generate ./' from repository root to regenerate.

package statetimelinepanelcfg

// Defines values for LegendDisplayMode.
const (
	LegendDisplayModeHidden LegendDisplayMode = "hidden"

	LegendDisplayModeList LegendDisplayMode = "list"

	LegendDisplayModeTable LegendDisplayMode = "table"
)

// Defines values for LegendPlacement.
const (
	LegendPlacementBottom LegendPlacement = "bottom"

	LegendPlacementRight LegendPlacement = "right"
)

// Defines values for SortOrder.
const (
	SortOrderAsc SortOrder = "asc"

	SortOrderDesc SortOrder = "desc"

	SortOrderNone SortOrder = "none"
)

// Defines values for TimelineValueAlignment.
const (
	TimelineValueAlignmentCenter TimelineValueAlignment = "center"

	TimelineValueAlignmentLeft TimelineValueAlignment = "left"

	TimelineValueAlignmentRight TimelineValueAlignment = "right"
)

// Defines values for TooltipDisplayMode.
const (
	TooltipDisplayModeMulti TooltipDisplayMode = "multi"

	TooltipDisplayModeNone TooltipDisplayMode = "none"

	TooltipDisplayModeSingle TooltipDisplayMode = "single"
)

// Defines values for VisibilityMode.
const (
	VisibilityModeAlways VisibilityMode = "always"

	VisibilityModeAuto VisibilityMode = "auto"

	VisibilityModeNever VisibilityMode = "never"
)

// TODO docs
type HideSeriesConfig struct {
	Legend  bool `json:"legend"`
	Tooltip bool `json:"tooltip"`
	Viz     bool `json:"viz"`
}

// TODO docs
type HideableFieldConfig struct {
	// TODO docs
	HideFrom *HideSeriesConfig `json:"hideFrom,omitempty"`
}

// TODO docs
// Note: "hidden" needs to remain as an option for plugins compatibility
type LegendDisplayMode string

// TODO docs
type LegendPlacement string

// TODO docs
type OptionsWithLegend struct {
	// TODO docs
	Legend VizLegendOptions `json:"legend"`
}

// TODO docs
type OptionsWithTimezones struct {
	Timezone *[]TimeZone `json:"timezone,omitempty"`
}

// TODO docs
type OptionsWithTooltip struct {
	// TODO docs
	Tooltip VizTooltipOptions `json:"tooltip"`
}

// PanelFieldConfig defines model for PanelFieldConfig.
type PanelFieldConfig struct {
	// Embedded struct due to allOf(#/components/schemas/HideableFieldConfig)
	HideableFieldConfig `yaml:",inline"`
}

// PanelOptions defines model for PanelOptions.
type PanelOptions struct {
	// Embedded struct due to allOf(#/components/schemas/OptionsWithLegend)
	OptionsWithLegend `yaml:",inline"`
	// Embedded struct due to allOf(#/components/schemas/OptionsWithTooltip)
	OptionsWithTooltip `yaml:",inline"`
	// Embedded struct due to allOf(#/components/schemas/OptionsWithTimezones)
	OptionsWithTimezones `yaml:",inline"`
	// Embedded fields due to inline allOf schema
}

// TODO docs
type SortOrder string

// A specific timezone from https://en.wikipedia.org/wiki/Tz_database
type TimeZone interface{}

// Controls the value alignment in the TimelineChart component
type TimelineValueAlignment string

// TODO docs
type TooltipDisplayMode string

// TODO docs
type VisibilityMode string

// TODO docs
type VizLegendOptions struct {
	AsTable *bool    `json:"asTable,omitempty"`
	Calcs   []string `json:"calcs"`

	// TODO docs
	// Note: "hidden" needs to remain as an option for plugins compatibility
	DisplayMode LegendDisplayMode `json:"displayMode"`
	IsVisible   *bool             `json:"isVisible,omitempty"`

	// TODO docs
	Placement  LegendPlacement `json:"placement"`
	ShowLegend bool            `json:"showLegend"`
	SortBy     *string         `json:"sortBy,omitempty"`
	SortDesc   *bool           `json:"sortDesc,omitempty"`
	Width      *float32        `json:"width,omitempty"`
}

// TODO docs
type VizTooltipOptions struct {
	// TODO docs
	Mode TooltipDisplayMode `json:"mode"`

	// TODO docs
	Sort SortOrder `json:"sort"`
}
