// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by pipeline:
//     go
// Using jennies:
//     TypedSchemaJenny
//     LatestMajorsOrXJenny
//
// Run 'go generate ./' from repository root to regenerate.

package publicdashboard

import (
	"fmt"
	"sync"

	"github.com/grafana/grafana/pkg/registry/corekind"
	"github.com/grafana/thema"
)

// KindVersion is the syntactic version of the canonical schema from which this
// package's '[PublicDashboard] type was generated.
//
// This value will always be the same as calling Schema().Version().
var KindVersion thema.SyntacticVersion = [2]uint{0, 0}

var schemaOnce sync.Once
var tschema thema.TypedSchema[*PublicDashboard]

// Schema returns the [thema.TypedSchema] representing the schema from which
// the [PublicDashboard] type and its referenced subtypes (if any) were generated.
func Schema() thema.TypedSchema[*PublicDashboard] {
	reg := corekind.NewBase(nil)
	sch := thema.SchemaP(reg.PublicDashboard().Lineage(), thema.SV(0, 0))
	schemaOnce.Do(func() {
		var err error
		tschema, err = thema.BindType[*PublicDashboard](sch, new(PublicDashboard))
		if err != nil {
			panic(fmt.Sprintf("publicdashboard@0.0 is not assignable to *publicdashboard: %s", err))
		}
	})
	return tschema
}

// NewWithDefaults returns a new [PublicDashboard] that has been initialized with
// schema-specified default values.
func NewWithDefaults() *PublicDashboard {
	return Schema().NewT()
}
