export class RowPanelBuilder extends OptionsBuilder<RowPanel> {
	internal: RowPanel;

	build(): RowPanel {
		return this.internal;
	}

	// The panel type
	withType(typeArg: string): this {
		
		this.internal.type = typeArg;

		return this;
	}

	// Whether this row should be collapsed or not.
	withCollapsed(collapsed: boolean): this {
		
		this.internal.collapsed = collapsed;

		return this;
	}

	// Row title
	withTitle(title: string): this {
		
		this.internal.title = title;

		return this;
	}

	// Name of default datasource for the row
	withDatasource(datasource: DataSourceRef): this {
		
		this.internal.datasource = datasource;

		return this;
	}

	// Row grid position
	withGridPos(gridPos: GridPos): this {
		
		this.internal.gridPos = gridPos;

		return this;
	}

	// Unique identifier of the panel. Generated by Grafana when creating a new panel. It must be unique within a dashboard, but not globally.
	withId(id: number): this {
		
		this.internal.id = id;

		return this;
	}

	// List of panels in the row
	withPanels(panels: Panel[]): this {
		
		this.internal.panels = panels;

		return this;
	}

	// Name of template variable to repeat for.
	withRepeat(repeat: string): this {
		
		this.internal.repeat = repeat;

		return this;
	}

}
